environment:
  matrix:
    - nodejs_version: '10.16.0'

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm test

build: off
